POST http://localhost:3000/user
Content-Type: application/json

{
    "username": "phamn23",
    "password": "Hello World"
}

### 

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "phamn23",
    "password": "Hello World"
}

### 

GET http://localhost:3000/user/logout

###

POST http://localhost:3000/bin

### 

GET http://localhost:3000/bin/64625ae60be82d87504792f6


### 

GET http://localhost:3000/bins

### 

DELETE http://localhost:3000/bin/6461ab4871036bcdc3c6d5c5