### Create a new user
POST http://localhost:3000/api/v1/user
Content-Type: application/json

{ 
    "username": "Nathan", 
    "password": "Hello World",
    "confirmPassword": "Hello World"
}

### Login user
POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{ 
    "username": "Nathan", 
    "password": "Hello World" 
}

### Logout user
GET http://localhost:3000/api/v1/user/logout

